version: "3.9"
services:
  website:
    image: dgimbialo/site:v1
    ports:
      - "80:80"    
    links:
        - server
  server:
    image: dgimbialo/server:v1
    container_name: server
    ports:
      - "8081:8081"
      - "5000:5000"
    restart: always
    links: 
      - react_admin   
  react_admin:
    image: dgimbialo/react-admin:v1
    container_name: reactAdmin
    ports:
    - "3000:3000"
    restart: always  
